### ISSUE TITLE
manifest names are hashed aswell

### ISSUE THREAD

**Issue by philipp-winterle** [nystudio107/save-remote-file-webpack-plugin#1]
Config like this:
```javascript
new SaveRemoteFilePlugin([
          {
              url: 'https://google-analytics.com/analytics.js',
              filepath: 'xjs/external/analytics.js',
          }
]),
```

results in manifest like this: 

```javascript
"xjs/external/analytics.0ea40a4cb2873a89cbe597eaea860826.js": "/xjs/external/analytics.0ea40a4cb2873a89cbe597eaea860826.js",
```

Example shows the valid name without hash.

**Comment by khalwat** [comment]
This is not happening for me --

```json
  "js/analytics.js": "/dist/js/analytics.af5c617d36e28d19710b882a6824e213.js",
```

Do you have any steps to reproduce?

**Comment by allegretti** [comment]
Other problem, but I think it is related...
Config:

`new SaveRemoteFilePlugin([
      {
        url: 'https://fairplayds.zeroheight.com/api/design_tokens?auth={myAuthHere}&format=json&id={myId}&dl=1',
        filepath: '../src/common/ds-tokens.json',
        hash: false,
      },
    ]),`

Hash is generated anyway...

`ds-tokens.19710b8382a6728af5c6214e18d2d36e.json`

I don't using manifest... 

After forking the repository and removing the "appendHashToPath" method outside, it is working as I need it. Unfortunately, I have no time to properly solve the problem and open a PR for you right now = (
