### ISSUE TITLE
Can I run 'SaveRemoteFilePlugin' as a function 

### ISSUE THREAD

**Issue by ghost** [nystudio107/save-remote-file-webpack-plugin#11]
I want to run the function to download some resources before even build process.
Coupled with [WebpackBeforeBuildPlugin](https://www.npmjs.com/package/before-build-webpack) or other ways.

thanks a lot !

**Comment by khalwat** [comment]
Unfortunately this plugin probably isn't what you want, but you could probably adapt it to run at a different phase in the build cycle, if you wanted to fork it.
