### ISSUE TITLE
Add support to webpack 5

### ISSUE THREAD

**Issue by RodrigoTomeES** [nystudio107/save-remote-file-webpack-plugin#16]
### Is your feature request related to a problem? Please describe.

The plugin throw an error on webpack 5

### Additional context

(node:17996) DeprecationWarning: Hook.context is deprecated and will be removed
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:17996) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.

**Comment by khalwat** [comment]
Yes, this is a deprecation error that will need to be fixed for Webpack 6 (whenever it comes out). It still works with webpack 5 however.
