### ISSUE TITLE
Version 1.1.0 not on npm

### ISSUE THREAD

**Issue by sebikovacs** [nystudio107/save-remote-file-webpack-plugin#6]
### Question
I was wondering if there is a reason why version 1.1.0 is not on npm. I would like to use this plugin with the hash option turned off but the latest version on npm is 1.0.2

**Comment by Fryguy** [comment]
+1, would love to have the hash option. @khalwat can we get a 1.1.0 release?

**Comment by khalwat** [comment]
Ah sorry, I will get that rectified

**Comment by Fryguy** [comment]
Hi @khalwat ...not trying to be a pain but any updates?

**Comment by khalwat** [comment]
Thx for the reminder... published! https://www.npmjs.com/package/save-remote-file-webpack-plugin
